include: package:effective_dart/analysis_options.1.3.0.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    public_member_api_docs: error

linter:
  rules:
    # Back to the 80s? No!
    lines_longer_than_80_chars: false
